#ifndef __LOCAL_MAP_H__
#define __LOCAL_MAP_H__

#define GRID_SIZE 10
#define GRID_WIDTH 120
#define GRID_HEIGHT 120

#define GRASS_X_DISTANCE_TO_CHECK  4
#define GRASS_Y_DISTANCE_TO_CHECK  4

#define GRASS_BREAK_THRESHOLD 0.8

#define GRASS_NOTICE_DELAY 300  // 1500

#endif
